In [4]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
arr1=arr.reshape(3,2) #reshaping arr(2,3) to arr1(3,2) 

In [9]:
print(arr1)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
print(arr.ndim

2


In [11]:
print(arr1.ndim) #ndim is the dimention of matrix

2


In [13]:
print(arr.itemsize) #itemsize means byte size of each element

4


In [14]:
print(arr.dtype) #dtype is datatype od each element in matrix

int32


In [16]:
print(arr.size) # size means no of elemet in matrix

6


In [17]:
print(arr.shape) #shape of matrix

(2, 3)


In [18]:
import numpy as np

a=np.array([(1,2,3,4),(3,4,5,6)])

print(a)

[[1 2 3 4]
 [3 4 5 6]]


In [19]:
print(a[0,2])

3


In [20]:
print(a[0:,3])

[4 6]


In [22]:
print(a[0:2,3])

[4 6]


In [26]:
import numpy as np
a=np.linspace(1,3,5)
print(a)

[1.  1.5 2.  2.5 3. ]


In [2]:
import numpy as np
b=np.array([1,2,3,4])
print(b.min())
print(b.max())
print(b.sum())

1
4
10


In [13]:
z=np.zeros((3,3), dtype= int)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [38]:
e=np.random.randint(9, size=(3,3))
print(e)

[[0 2 6]
 [1 8 4]
 [7 0 8]]


In [36]:
f=np.arange(0,30,5) #arange(start,End,Step-Size)
print(f)

print("---------------------")
g=f.reshape(2,3)
print(g)

print("---------------------")
h=g.flatten() # flatten is use for convert to flat array form of any type of matrix
print(h)

[ 0  5 10 15 20 25]
---------------------
[[ 0  5 10]
 [15 20 25]]
---------------------
[ 0  5 10 15 20 25]


In [1]:
print("The End")

The End
